config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'
  
  resources :working, param: :slug
  resources :writing, param: :slug
  resources :messages

  root 'welcome#index'

end

app/models/working.rb
class Working < ActiveRecord::Base
  has_attached_file :image, 
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join('config/dropbox.yml'),
    :dropbox_options => {},
    :default_url => "http://dummyimage.com/200"

  validates_presence_of :title, :subtitle, :slug, :body
  validates :slug, uniqueness: { case_sensitive: false }, format: { with: Regexp.new('\A' + Elnazis::SLUG_FORMAT.source + '\z') }
  validates_attachment :image, :presence => true, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }
  
  def to_param
    slug
  end
end

app/models/writing.rb
class Writing < ActiveRecord::Base
  has_attached_file :image, 
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join('config/dropbox.yml'),
    :dropbox_options => {},
    :default_url => "http://dummyimage.com/200"

  validates_presence_of :title, :slug, :body, :published_at
  validates :slug, uniqueness: { case_sensitive: false }, format: { with: Regexp.new('\A' + Elnazis::SLUG_FORMAT.source + '\z') }
  validates_attachment :image, :presence => true, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }
  
  def to_param
    slug
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @writings = Writing.order(published_at: :desc).first(4)
    @workings = Working.order(:sort_order).first(6)
  end
end

app/controllers/working_controller.rb
class WorkingController < ApplicationController
  
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"], except: [:index, :show]
  
  def index
    @workings = Working.all.order(:sort_order)
  end
  
  def show
	  @working = Working.find_by_slug(params[:slug])
	end
  
  def new
	  @working = Working.new
	end
	
	def edit
	  @working = Working.find_by_slug(params[:slug])
	end
	
	def create
	  @working = Working.new(working_params)
	  
	  if @working.save
	  	redirect_to @working
	  else
	    render 'new'
	  end
	end
	
	def update 
	  @working = Working.find_by_slug(params[:slug])
	  
	  if @working.update(working_params)
	    redirect_to @working
	  else
	    render 'edit'
	  end
	end
	
	def destroy
	  @working = Working.find_by_slug(params[:slug])
	  @working.destroy
	  
	  redirect_to working_index_path
	end
	
	private
	  def working_params
	  	params.require(:working).permit(:title, :subtitle, :slug, :body, :sort_order, :image)
	  end
end

app/controllers/writing_controller.rb
class WritingController < ApplicationController
	
	http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"], except: [:index, :show]

	def index
	  @writings = Writing.all.order(published_at: :desc)
	end
	
	def show
	  @writing = Writing.find_by_slug(params[:slug])
	end
	
	def new
	  @writing = Writing.new
	end
	
	def edit
	  @writing = Writing.find_by_slug(params[:slug])
	end
	
	def create
	  @writing = Writing.new(writing_params)
	  
	  if @writing.save
	  	redirect_to @writing
	  else
	    render 'new'
	  end
	end
	
	def update 
	  @writing = Writing.find_by_slug(params[:slug])
	  
	  if @writing.update(writing_params)
	    redirect_to @writing
	  else
	    render 'edit'
	  end
	end
	
	def destroy
	  @writing = Writing.find_by_slug(params[:slug])
	  @writing.destroy
	  
	  redirect_to writing_index_path
	end
	
	private
	  def writing_params
	  	params.require(:writing).permit(:title, :slug, :body, :image, :published_at)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navClass(controller)
    "current" if params[:controller] == controller || request.path.start_with?('/' + controller)
  end
  
  def title(page_title)
    content_for (:title) { page_title }
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/working_helper.rb
module WorkingHelper
end

app/helpers/writing_helper.rb
module WritingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield (:title) %></title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
  <meta name="google-site-verification" content="gpemUCDpS30H2ndYB97Q28zQE2NvBxn9Ki853gGudn8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#76B543">
</head>
<body>
	<div id="body">
		<div id="header">
			<div id="logo"><span><a href="<%= root_path %>">em</a> elnaz moshfeghian</span></div>
			<a href="#" id="menu-toggle">Menu</a>
			<div id="nav">
				<ul class="nav-content">
					<li><%= link_to 'Home', root_path, class: navClass('welcome') %></li>
					<li><%= link_to 'Blog', writing_index_path, class: navClass('writing') %></li>
					<li><%= link_to 'Portfolio', working_index_path, class: navClass('working') %></li>
					<li><%= link_to 'About', about_path, class: navClass('about') %></li>
				</ul>
			</div>
			<div class="clear"></div>
		</div>

		<%= yield %>

	</div>

	<div id="footer">
		<ul id="contact-links">
			<li><a href="https://github.com/elnaz"><i class="fa fa-github fa-2x"></i></a></li>
			<li><a href="https://twitter.com/elnazem"><i class="fa fa-twitter fa-2x"></i></a></li>
			<li><a href="https://www.linkedin.com/in/elnazm"><i class="fa fa-linkedin fa-2x"></i></a></li>
			<li><a href="https://plus.google.com/+ElnazMoshfeghian"><i class="fa fa-google-plus fa-2x"></i></a></li>
			<li><a href="http://instagram.com/elnazem"><i class="fa fa-instagram fa-2x"></i></a></li>
			<li><a href="https://bitbucket.org/elnaz"><i class="fa fa-bitbucket fa-2x"></i></a></li>
		</ul>
    </div>

	<div id="menu" class="">
		<ul class="nav-content">
			<li class=<%= navClass('welcome') %>><i class="fa fa-home"></i><%= link_to 'Home', root_path %></li>
			<li class=<%= navClass('writing') %>><i class="fa fa-newspaper-o"></i><%= link_to 'Blog', writing_index_path %></li>
			<li class=<%= navClass('working') %>><i class="fa fa-bullhorn"></i><%= link_to 'Portfolio', working_index_path %></li>
			<li class=<%= navClass('about') %>><i class="fa fa-info-circle"></i><%= link_to 'About', about_path %></li>
			<li><i class="fa fa-send-o"></i><%= link_to 'Contact', '#contact' %></li>
		</ul>
	</div>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/static_pages/about.html.erb
<% title "About" %>

<h1 class="index-title"><%= yield :title %></h1>
<div class="about c3-4">
	<p>I build for the web. I craft product and feature ideas, conduct design research, generate wireframes, commit full-stack code, write copy, perform unit and usability testing, and roll out web applications to users.</p>
	<p>My work includes a <%= link_to "data visualization website", Working.find_by_slug("schoolcuts") %> to dissect the 2013 Chicago Public School closings, a <%= link_to "crowdfunding platform", Working.find_by_slug("benevolent") %> for individuals working with social service organizations to get their life on track, and a <%= link_to "collaboration app", Working.find_by_slug("arctic-collaborations") %> to accelerate the pace of Arctic research.</p>
	<p>I've lived in seven cities spanning five countries and three continents. Those experiences have prepared me well for the fast-paced, cross-functional, ambiguity-rich work of design, software engineering, and product management.</p>
	<!-- <p>In addition to getting a Bachelor's of Computer Science at <a href="http://iit.edu">Illinois Tech</a>, she was the President of the Student Government Association. Elnaz represented the interests of 7,000 undergraduate and graduate students and led the 50 elected and appointed officers serving them.</p> -->
	<p>I make the most of my offline time with rock climbing, bike commuting, reading, making playlists, and traveling.</p>
</div>

app/views/welcome/index.html.erb
<% title "Elnaz Moshfeghian" %>

<p id="intro">Software engineer, product manager, and community organizer. Living in San Francisco since April '15. Before that: Chicago, Oklahoma, Kuwait, Qatar, Australia, and Iran. I climb rocks, ride bikes, watch movies, talk civics, and follow the NBA.</p>	
<div class="clear"></div>

<h2>Blog</h2>
<%= render 'writing/list' %>
<% if Writing.count > 4 %>
  <p class="more-items"><%= link_to raw('Read more <i class="fa fa-angle-right"></i>'), writing_index_path %></p>
<% end %>

<h2>Portfolio</h2>
<%= render 'working/list' %>
<% if Working.count > 6 %>
  <p class="more-items"><%= link_to raw('View more <i class="fa fa-angle-right"></i>'), working_index_path %></p>
<% end %>

app/views/working/_form.html.erb
<%= form_for @working do |f| %>  
  <% if @working.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@working.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
  		<% @working.errors.full_messages.each do |msg| %>
  		  <li><%= msg %></li>
  		<% end %>    
      </ul>
    </div>
  <% end %>
  
  <dl class="form">
    <dt><%= f.label :title %></dt>
  	<dd class="field"><%= f.text_field :title, :class => 'txt-med' %></dd>
  	
  	<dt><%= f.label :subtitle %></dt>
  	<dd class="field"><%= f.text_field :subtitle, :class => 'txt-med' %></dd>	 
  	
  	<dt><%= f.label :slug %></dt>
  	<dd class="field"><%= f.text_field :slug, :class => 'txt-med' %></dd>
  	
  	<dt><%= f.label :body %></dt>
  	<dd class="field"><%= f.text_area :body, :class => 'txt', :rows => 15 %></dd>  
  	
  	<dt><%= f.label :sort_order %></dt>
  	<dd class="field"><%= f.text_field :sort_order, :class => 'txt-num' %></dd>
  	
  	<dt><%= f.label :image %></dt>
  	<dd class="field"><%= f.file_field :image %></dd>
  	
  	<dt></dt>
  	<dd class="field"><%= f.submit 'Save', :class => 'btn' %> <%= link_to 'Cancel', working_index_path %></dd>
  </dl>
<% end %>
<div class="clear"></div>

app/views/working/_list.html.erb
<ul class="projects">
	<% @workings.each do |working| %>
	<li>
		<a href="<%= working_path(working) %>">
		  <%= image_tag working.image.url, :alt => working.title %>
			<p class="title"><%= working.title %></p>
			<p class="subtitle"><%= working.subtitle %></p>
		</a>
	</li>	
	<% end %>
</ul>
<div class="clear"></div>

app/views/working/edit.html.erb
<% title 'Edit project' %>
<h1><%= yield :title %></h1>

<%= render 'form' %>

<span class="r"><%= link_to 'Delete', working_path(@working), method: :delete, data: { confirm: 'Are you sure?' } %></span>

app/views/working/index.html.erb
<% title "Portfolio" %>

<h1 class="index-title"><%= yield :title %></h1>
<%= render 'working/list' %>

app/views/working/new.html.erb
<% title 'New project' %>
<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/working/show.html.erb
<% title @working.title %>

<h1><%= yield :title %></h1>

<div id="project-body">
	<%= raw @working.body %>
</div>

<div class="clear"></div>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'elnazis'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/writing/_form.html.erb
<%= form_for @writing do |f| %>  
  <% if @writing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@writing.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
  		<% @writing.errors.full_messages.each do |msg| %>
  		  <li><%= msg %></li>
  		<% end %>    
      </ul>
    </div>
  <% end %>
  
  <dl class="form">
    <dt><%= f.label :title %></dt>
  	<dd class="field"><%= f.text_field :title, :class => 'txt-med' %></dd>	 
  	
  	<dt><%= f.label :slug %></dt>
  	<dd class="field"><%= f.text_field :slug, :class => 'txt-med' %></dd>
  	
  	<dt><%= f.label :body %></dt>
  	<dd class="field"><%= f.text_area :body, :class => 'txt', :rows => 15 %></dd>
  	
  	<dt><%= f.label :image %></dt>
  	<dd class="field"><%= f.file_field :image %></dd>
  	 
  	<dt><%= f.label :published_at %></dt>
  	<dd class="field"><%= f.date_field :published_at, :prompt => Time.now.strftime('%Y-%m-%d') %></dd>	 
  	
  	<dt></dt>
  	<dd class="field"><%= f.submit 'Save', :class => 'btn' %> <%= link_to 'Cancel', writing_index_path %></dd>
  </dl>
<% end %>
<div class="clear"></div>

app/views/writing/_list.html.erb
<ul class="posts">
	<% @writings.each do |writing| %>
	<li>
		<a href="<%= writing_path(writing) %>">
			<%= image_tag writing.image.url, :alt => writing.title %>
			<p class="title"><%= writing.title %></p>
			<p class="date"><%= writing.published_at.strftime("%b %-d, %Y") %></p>
		</a>
	</li>	
	<% end %>
</ul>
<div class="clear"></div>

app/views/writing/edit.html.erb
<% title 'Edit writing' %>
<h1><%= yield :title %></h1>

<%= render 'form' %>

<span class="r"><%= link_to 'Delete', writing_path(@writing), method: :delete, data: { confirm: 'Are you sure?' } %></span>

app/views/writing/index.html.erb
<% title "Blog" %>

<h1 class="index-title"><%= yield :title %></h1>
<%= render 'writing/list' %>

app/views/writing/new.html.erb
<% title 'New writing' %>
<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/writing/show.html.erb
<% title @writing.title %>

<h1 id="post-title"><%= yield :title %></h1>
			
<p class="mute" id="post-date"><%= raw @writing.published_at.strftime("%b %-d, %Y") %></p>

<div id="post-body">
	<%= raw @writing.body %>
</div>

<div class="clear"></div>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'elnazis'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>